---
name: Sync Fork

# yamllint disable-line rule:truthy
on:
  schedule:
    # yamllint disable-line rule:comments
    - cron: "0 3 * * *" # daily at 3
  # yamllint disable-line rule:comments
  workflow_dispatch: # on button click

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - uses: tgymnich/fork-sync@v1.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          owner: hassio-addons
          base: main
          head: main
